language: node_js
node_js:
- 8
- 6
- node
os:
- linux
- osx
osx_image: xcode7.3
before_install: npm install --global greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script: yarn run travis
after_script: greenkeeper-lockfile-upload
after_success:
- yarn global add codecov
- codecov
cache:
  yarn: true
branches:
  only:
  - master
  - "/^greenkeeper/.*$/"
env:
  global:
    secure: AFR8KvRS3A58pv3k96/Zuj+7pqlDUDZsQgcL+o++2zyDVXpFJpHMSGRy3qEpCiVp+k8HxXjiw+dRDBYkDOrEQXZ0gaiAVeyl+19VO0XXLw0KmCW8kRNajsg2g2b4+2CWos7JowMgqPQLJRosm0qyojiBSzKlzrW4be34PqtoCA0K6SQ6fKnge6nW9iU6yUJHm3fG4tqDNu5BB2A5PuC9KwVY51dj627faKfVvsVOpbBSH6imy9o3NsZvp5pmB3KvvH/ISxvaMh42FSM/NmIemkMsyxlS5ZOuJFKM3NvXQSBp6rUY5eUp/S4O3PzZIiNQSPbJXA2lPVkQIeiPyTX2dZ3ssHcmYZeFm3OxIlq1SNORp659K+mCAiRLuY2WyWLh6zJtedCUlN/Q1+WILm4aXNXl5RbBr3DMPhM/ELXD37Pg/JTSdgDI6NUgF/OZ2PJu/Dr76Q4gtF6BQemk8MkJ1X6Q/JZDIp4XDMB9WZHqQARk4nCqQnjJyQXoYiwsHN5cquFpdD6aMJLTzFZB3DiqcN3caEO0TfFG0adq2cvk5HfRkEs9m4oKQw9j6n1IyWtJzy/P0acoqjmFSmh5AdOchIUB/dkVWsYek4gGFIWoV6erPgUhJ1KDAVUYoXHI5Q7RQItCWtEF3BJ8J2r4ez0KoFcobpnc1OBPsnSrXdWNB04=
